# name: Build and Deploy
# on:
#   push:
#     branches:
#       - main
#     tags:
#       - v*.*.*
#     workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Build
#         run: echo "Building..."
#       - name: Deploy
#         run: echo "Deploying..."